# Generated by Django 6.1.1 on 2026-09-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='reminder_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
