# Generated by Django 5.2.7 on 2026-09-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default='', max_length=60, unique=True),
        ),
    ]
