# Generated by Django 6.1.1 on 2026-09-20 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_username_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
