# Generated by Django 6.1.1 on 2026-09-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_request', 'Appointment Request'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_rejected', 'Appointment Rejected'), ('appointment_reminder', 'Appointment Reminder'), ('review', 'Review'), ('system', 'System')], db_index=True, default='system', max_length=30),
        ),
    ]
