# Generated by Django 6.1.1 on 2026-09-19 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='hospitals.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-appointment_date', '-start_time'),
                'indexes': [models.Index(fields=['doctor', 'appointment_date', 'status'], name='appointment_doctor__f0e3f4_idx'), models.Index(fields=['patient', 'appointment_date', 'status'], name='appointment_patient_90578b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='appointment_end_after_start'), models.UniqueConstraint(condition=models.Q(('status__in', ('cancelled', 'rejected')), _negated=True), fields=('doctor', 'appointment_date', 'start_time'), name='uniq_live_doctor_slot')],
            },
        ),
    ]
