# Generated by Django 6.1.1 on 2026-09-21 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_type', models.CharField(choices=[('1h', '1 hour before'), ('24h', '24 hours before'), ('1w', '1 week before')], db_index=True, max_length=5)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('sent', models.BooleanField(db_index=True, default=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment')),
            ],
            options={
                'ordering': ('scheduled_for',),
                'constraints': [models.UniqueConstraint(fields=('appointment', 'reminder_type'), name='uniq_appointment_reminder_type')],
            },
        ),
    ]
