# Generated by Django 5.2.7 on 2026-09-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointmentreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='video_session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
