# Generated by Django 5.2.7 on 2026-09-22 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_video_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='video_session_id',
        ),
    ]
