# Generated by Django 6.1.1 on 2026-09-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=16)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('location_details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
