# Generated by Django 5.2.7 on 2026-09-19 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_availabilitybreak_scheduleexception'),
        ('hospitals', '0002_seed_hospitals'),
        ('specialties', '0002_seed_specialties_hospitals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['doctor', 'weekday', 'is_active'], name='avail_dk_wd_act_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_available', 'average_rating'], name='dr_avail_rat_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleexception',
            index=models.Index(fields=['doctor', 'date'], name='sched_exc_dk_dt_idx'),
        ),
    ]
