# Generated by Django 6.1.1 on 2026-09-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='office_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
