# Generated by Django 5.2.7 on 2026-09-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0002_seed_specialties_hospitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='patient_friendly_name',
            field=models.CharField(blank=True, default='', help_text="Plain-language name patients understand (e.g. 'Children's doctor' for Pediatrics).", max_length=150),
        ),
        migrations.AddField(
            model_name='specialty',
            name='what_to_expect',
            field=models.TextField(blank=True, default='', help_text='Patient-friendly explanation: what problems this doctor handles, symptoms to watch for.'),
        ),
    ]
